name: Deploy Demo to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Clear pnpm cache
        run: |
          pnpm store prune
          pnpm store prune --force

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --prefer-offline=false

      - name: Check installed version
        run: pnpm list user-copilot-ui

      - name: Build demo
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: demo/dist
