name: Publish NPM if version changed

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm run build
      - name: Check if version is published
        id: check_version
        run: |
          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VERSION=$(node -p "require('./package.json').version")
          NPM_VERSION=$(npm view $PKG_NAME version || echo "0.0.0")
          echo "pkg_version=$PKG_VERSION" >> $GITHUB_OUTPUT
          echo "npm_version=$NPM_VERSION" >> $GITHUB_OUTPUT
      - name: Publish if version changed
        if: steps.check_version.outputs.pkg_version != steps.check_version.outputs.npm_version
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
